---
- name: "Setup.yml"
  hosts: localhost
  gather_facts: yes

  tasks:
  - name: Colorize root shell prompt
    lineinfile:
      path: /root/.bashrc
      line: 'export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"'
      state: present

  - name: Install packages (Rocky)
    dnf:
      name: 
      - bash-completion
      - curl
      - git
      - rsync
      - vim
      - wget
      state: latest      
    when: ansible_distribution == "Rocky"
