# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.

# Documentantion - Packer: https://developer.hashicorp.com/packer/plugins/builders/proxmox

variable "os_image" {
  type    = string
  default = "Rocky-x86_64-dvd.iso"
}

variable "proxmox_api_token_id" {
  type    = string
}

variable "proxmox_api_token_secret" {
  type    = string
  sensitive = true
}

variable "proxmox_api_url" {
  type    = string
}

variable "proxmox_iso_pool" {
  type    = string
  default = "local:iso"
}

variable "proxmox_node" {
  type    = string
}

variable "proxmox_storage_format" {
  type    = string
  default = "raw"
}

variable "proxmox_storage_pool" {
  type    = string
  default = "local-lvm"
}

variable "proxmox_storage_pool_type" {
  type    = string
  default = "lvm-thin"
}

variable "ssh_password" {
  type    = string
  sensitive = true
}

variable "template_description" {
  type    = string
  default = "Rocky Linux 9 Template"
}

variable "template_name" {
  type    = string
  default = "RL9-Template"
}

variable "version" {
  type    = string
  default = ""
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source

source "proxmox" "rocky-linux-9-base" {
  username            = "${var.proxmox_api_token_id}"
  token               = "${var.proxmox_api_token_secret}"
  boot_command        = ["<tab> text inst.ks=https://raw.githubusercontent.com/ArdRay/packer_templates/master/rocky-linux-9/http/rl9-base.ks<enter><wait>"]
  boot_wait           = "4s"
  cores               = "2"
  cpu_type            = "host"
  disks {
    disk_size         = "32G"
    format            = "${var.proxmox_storage_format}"
    storage_pool      = "${var.proxmox_storage_pool}"
    storage_pool_type = "${var.proxmox_storage_pool_type}"
    type              = "scsi"
  }
  http_directory           = "http"
  insecure_skip_tls_verify = false
  iso_file                 = "${var.proxmox_iso_pool}/${var.os_image}"
  memory                   = "4096"
  network_adapters {
    model  = "virtio"  
    bridge = "vmbr0"
    firewall = true
  }
  node                 = "${var.proxmox_node}"
  os                   = "l26"
  proxmox_url          = "${var.proxmox_api_url}"
  scsi_controller      = "virtio-scsi-single"
  ssh_password         = "${var.ssh_password}"
  ssh_port             = 22
  ssh_timeout          = "15m"
  ssh_username         = "root"
  template_description = "${var.template_description}"
  template_name        = "${var.template_name}"
  
  unmount_iso          = true
  
  vm_id                = "140"
  vm_name              = "rocky-linux-9-test"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.proxmox.rocky-linux-9-base"]

  provisioner "shell" {
    inline = [
      "yum install -y cloud-init qemu-guest-agent cloud-utils-growpart gdisk", 
      "systemctl enable qemu-guest-agent", 
      "shred -u /etc/ssh/*_key /etc/ssh/*_key.pub", 
      "rm -f /var/run/utmp /var/log/lastlog /var/log/wtmp /var/log/btmp", 
      "rm -rf /tmp/* /var/tmp/*", 
      "unset HISTFILE; rm -rf /home/*/.*history /root/.*history", 
      "rm -f /root/*ks", 
      "passwd -d root", 
      "passwd -l root", 
      "rm -f /etc/ssh/ssh_config.d/allow-root-ssh.conf"
    ]
    only   = ["proxmox"]
  }

}
